Set Shell zsh
Set Height 800
Output docs/docs/img/config-list.gif
Sleep 2.5s
Type "sunholo list-configs -h"
Enter
Sleep 5s
Type "sunholo list-configs"
Enter
Sleep 5s
Type "sunholo list-configs --kind 'vacConfig'"
Enter
Sleep 5s           
Type "sunholo list-configs --kind=vacConfig --vac=edmonbrain"
Enter
Sleep 5s       
Type "sunholo list-configs --kind=vacConfig --vac=edmonbrain --validate"
Enter
Sleep 5s

